{
 "title": "Agones Controller API Server Requests",
 "tags": [
  "agones",
  "controller",
  "server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "CustomResourceDefinition",
    "label": "CRD",
    "query": "fleets, gameservers, gameserversets, gameserverallocations"
   },
   {
    "name": "Subresource",
    "query": "\"status\", \"scale\", \"\""
   },
   {
    "name": "Verb",
    "query": {
     "query": "label_values(apiserver_request_total, verb)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Main Resource Request Count per Second",
   "type": "graph",
   "description": "API Server Main Resource Request count for Fleet/Gameserver/Gameserverset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=~\"[[CustomResourceDefinition]]\",verb!~\"WATCH|LIST\",subresource=~\"\"}[$__rate_interval])) by (resource,verb)",
     "legendFormat": "{{verb}} {{resource}}"
    }
   ]
  },
  {
   "title": "Subresource Request Count per Second",
   "type": "graph",
   "description": "API Server Subresource Request count for Fleet/Gameserver/Gameserverset",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=~\"[[CustomResourceDefinition]]\",verb!~\"WATCH|LIST\",subresource!~\"\"}[$__rate_interval])) by (resource,subresource,verb)",
     "legendFormat": "{{verb}} {{resource}} {{subresource}}"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=\"409\",resource=~\"[[CustomResourceDefinition]]\", subresource=~[[Subresource]]}[$__rate_interval])) by (code, resource, subresource)",
     "legendFormat": "{{resource}} {{subresource}} {{code}}"
    }
   ]
  },
  {
   "title": "Update Conflicts",
   "type": "graph",
   "description": "409 error on Update of Resources",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=\"409\",resource=~\"[[CustomResourceDefinition]]\",subresource=[[Subresource]]}[$__rate_interval])) by (code, resource, subresource)",
     "legendFormat": "{{resource}} {{subresource}}"
    }
   ]
  },
  {
   "title": "Request Latency 50%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{resource=~\"[[CustomResourceDefinition]]\", verb=~\"[[Verb]]\"}[$__rate_interval])) by (resource, subresource, verb, le)) * 1000",
     "legendFormat": "{{verb}} {{resource}} {{subresource}}"
    }
   ]
  },
  {
   "title": "Request Latency 90%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(apiserver_request_duration_seconds_bucket{resource=~\"[[CustomResourceDefinition]]\", verb=~\"[[Verb]]\"}[$__rate_interval])) by (resource, subresource, verb, le)) * 1000",
     "legendFormat": "{{verb}} {{resource}} {{subresource}}"
    }
   ]
  },
  {
   "title": "Request Latency 99%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{resource=~\"[[CustomResourceDefinition]]\", verb=~\"[[Verb]]\"}[$__rate_interval])) by (resource, subresource, verb, le)) * 1000",
     "legendFormat": "{{verb}} {{resource}} {{subresource}}"
    }
   ]
  }
 ]
}