{
 "title": "Agones GameServers",
 "tags": [
  "agones",
  "state",
  "gameservers"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "fleet",
    "query": "label_values(agones_gameservers_count, fleet_name)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "query": "label_values(agones_gameservers_count, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "GameServers count per type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_gameservers_count{fleet_name=~\"$fleet\", namespace=~\"$namespace\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "GameServers rate per type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_gameservers_total{fleet_name=~\"$fleet\", namespace=~\"$namespace\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "GameServers count per type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(agones_gameservers_count{fleet_name=~\"$fleet\", namespace=~\"$namespace\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fleet Replicas Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(agones_fleets_replicas_count{name=~\"$fleet\", namespace=~\"$namespace\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "GameServers per node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(agones_gameservers_node_count_bucket[1m])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(agones_gameservers_node_count_bucket[1m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(agones_gameservers_node_count_bucket[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(agones_gameservers_node_count_bucket[1m])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0, sum(rate(agones_gameservers_node_count_bucket[1m])) by (le))",
     "legendFormat": "min"
    },
    {
     "expr": "avg(delta(agones_gameservers_node_count_sum[1m]) / delta(agones_gameservers_node_count_count[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Node availability (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "agones_nodes_count{empty=\"true\"}",
     "legendFormat": "unused"
    },
    {
     "expr": "agones_nodes_count{empty=\"false\"}",
     "legendFormat": "used"
    }
   ]
  }
 ]
}