{
 "title": "Alpha - Agones Extensions Resource Usage",
 "tags": [ "controller" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Extensions Open File Descriptor Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{app=\"agones\",kubernetes_pod_name=~\"agones-extensions.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Last Go GC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds{app=\"agones\",agones_dev_role=\"extensions\"} * 1000",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Extensions Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"agones\",kubernetes_pod_name=~\"agones-extensions.*\"}",
     "legendFormat": "{{kubernetes_pod_name}} resident"
    },
    {
     "expr": "process_virtual_memory_bytes{app=\"agones\",agones_dev_role=\"extensions\"}",
     "legendFormat": "{{kubernetes_pod_name}} virtual"
    },
    {
     "expr": "go_memstats_alloc_bytes{app=\"agones\",agones_dev_role=\"extensions\"}",
     "legendFormat": "{{kubernetes_pod_name}} go_alloc"
    }
   ]
  },
  {
   "title": "Extensions Go Routines & Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "go_goroutines{app=\"agones\",agones_dev_role=\"extensions\"}",
     "legendFormat": "{{kubernetes_pod_name}} go_routines"
    },
    {
     "expr": "go_threads{app=\"agones\",agones_dev_role=\"extensions\"}",
     "legendFormat": "{{kubernetes_pod_name}} threads"
    }
   ]
  },
  {
   "title": "Controller CPU Used (% of core)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (irate (process_cpu_seconds_total{app=\"agones\",agones_dev_role=\"extensions\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Average Go GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " rate(go_gc_duration_seconds_sum{app=\"agones\",agones_dev_role=\"extensions\"}[5m]) / rate(go_gc_duration_seconds_count{app=\"agones\",agones_dev_role=\"extensions\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}} duration"
    }
   ]
  }
 ]
}