{
 "title": "Alpha - Agones Status",
 "description": "Agones CRD controller status",
 "tags": [
  "agones",
  "controller"
 ],
 "time": { "from": "2023-02-27T18:49:46.109Z", "to": "2023-02-27T18:59:46.109Z" },
 "templating": {
  "list": [
   {
    "name": "healthcheck",
    "query": {
     "query": "label_values(agones_healthcheck_status, check)\t"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{app=\"agones\",agones_dev_role=\"controller\"}) * 1000"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{app=\"agones\",agones_dev_role=\"controller\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Allocators Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((process_start_time_seconds{app=\"agones\",kubernetes_pod_name=~\"agones-allocator.*\"}) * 1000)"
    }
   ]
  },
  {
   "title": "Allocators Live Pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{app=\"agones\",multicluster_agones_dev_role=\"allocator\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Allocators Total Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{app=\"agones\",multicluster_agones_dev_role=\"allocator\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Extensions Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((process_start_time_seconds{app=\"agones\", agones_dev_role=\"extensions\"}) * 1000)"
    }
   ]
  },
  {
   "title": "Extensions Live Pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{app=\"agones\",agones_dev_role=\"extensions\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Extensions Total Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{app=\"agones\",agones_dev_role=\"extensions\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "repeat": "healthcheck",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  }
 ]
}