{
 "title": "Agones Controller go-client caches",
 "tags": [
  "controller",
  "agones",
  "client-go"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Last resource version",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "agones_k8s_client_cache_last_resource_version"
    }
   ]
  },
  {
   "title": "Cache items rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_k8s_client_cache_list_items_sum[5m]) / rate(agones_k8s_client_cache_list_items_count[5m]))",
     "legendFormat": "list items"
    },
    {
     "expr": "sum(rate(agones_k8s_client_cache_watch_events_sum[5m]) / rate(agones_k8s_client_cache_watch_events_count[5m]))",
     "legendFormat": "watch events"
    }
   ]
  },
  {
   "title": "Cache avg items per operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(agones_k8s_client_cache_list_items_sum / agones_k8s_client_cache_list_items_count)",
     "legendFormat": "list items"
    },
    {
     "expr": "sum(agones_k8s_client_cache_watch_events_sum / agones_k8s_client_cache_watch_events_count)",
     "legendFormat": "watch events"
    },
    {}
   ]
  },
  {
   "title": "Avg List/Watch requests duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_k8s_client_cache_list_duration_seconds_sum[5m]) / rate(agones_k8s_client_cache_list_duration_seconds_count[5m]))",
     "legendFormat": "list"
    },
    {
     "expr": "sum(rate(agones_k8s_client_cache_watch_duration_seconds_sum[5m]) / rate(agones_k8s_client_cache_watch_duration_seconds_count[5m]))",
     "legendFormat": "watch"
    }
   ]
  },
  {
   "title": "Caches operations rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_k8s_client_cache_list_total[1m]))",
     "legendFormat": "list"
    },
    {
     "expr": "sum(rate(agones_k8s_client_cache_watches_total[1m]))",
     "legendFormat": "watch"
    },
    {
     "expr": "sum(rate(agones_k8s_client_cache_short_watches_total[1m]))",
     "legendFormat": "short watch"
    }
   ]
  }
 ]
}